# uncommnet for localdev
#theme: minima
#theme: jekyll-theme-minima

#plugins:
#  - jekyll-remote-theme
#remote_theme: jekyll/minima

theme: minima
author: 
  name: Jim
  email: jimmyislive@gmail.com
title: How We AI
description: >
  A communityâ€‘driven collection of real, practical ways people use AI in their daily work and life.
exclude:
  - README.md
hide_site_feed_link: true
show_excerpts: true
